POST http://localhost:8080/api/event/create
Content-Type: application/json

{
  "name": "Show de Rock",
  "description": "Show ao vivo com bandas locais",
  "date": "2024-12-20T19:30:00",
  "location": "Espaço das Américas, São Paulo",
  "amountTickets": 500,
  "image": "https://exemplo.com/show.jpg"
}

###

GET http://localhost:8080/api/event?limit=2&pageToken=eyJpZCI6e319

###

GET http://localhost:8080/api/event/EVT-08c711d1-e1f6-495c-8a22-d20b67bf285a

###

DELETE http://localhost:8080/api/event/EVT-d00e7694-7c36-485f-a409-4ec067559b6d